/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

/**
 *
 * @author Kaspar
 */
public class HangmanGUI extends javax.swing.JFrame {

    Hangman MainC = new Hangman ();
    
    
    
    public HangmanGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Word = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TryLetter = new javax.swing.JTextField();
        CorrLetter = new javax.swing.JTextField();
        WrongLetter = new javax.swing.JTextField();
        Score = new javax.swing.JTextField();
        Check = new javax.swing.JButton();
        Tip = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        WordText = new javax.swing.JLabel();
        LetterText = new javax.swing.JLabel();
        CorrText = new javax.swing.JLabel();
        WrongText = new javax.swing.JLabel();
        ScoreText = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Word, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 220, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 170, 130));
        getContentPane().add(TryLetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, -1));
        getContentPane().add(CorrLetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 220, -1));
        getContentPane().add(WrongLetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, -1));
        getContentPane().add(Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 100, -1));

        Check.setText("Check");
        getContentPane().add(Check, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 70, -1));

        Tip.setText("Tip");
        getContentPane().add(Tip, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jButton1.setText("New Game");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 120, -1));

        WordText.setText("Word:");
        getContentPane().add(WordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 30, 20));

        LetterText.setText("Try a letter:");
        getContentPane().add(LetterText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        CorrText.setText("Correct letters:");
        getContentPane().add(CorrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        WrongText.setText("Wrong letters:");
        getContentPane().add(WrongText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 20));

        ScoreText.setText("Score:");
        getContentPane().add(ScoreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangmanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Check;
    private javax.swing.JTextField CorrLetter;
    private javax.swing.JLabel CorrText;
    private javax.swing.JLabel LetterText;
    private javax.swing.JTextField Score;
    private javax.swing.JLabel ScoreText;
    private javax.swing.JButton Tip;
    private javax.swing.JTextField TryLetter;
    private javax.swing.JTextField Word;
    private javax.swing.JLabel WordText;
    private javax.swing.JTextField WrongLetter;
    private javax.swing.JLabel WrongText;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
